### ISSUE TITLE
Geckodriver Binary Location

### ISSUE THREAD

**Issue by stanfordwong6** [SergeyPirogov/webdriver_manager#222]
When I set: os.environ['WDM_LOCAL'] = '1', the binaries are all still stored in the same location instead of in each project location.  It stores it in the virtualenv/bin directory.

The WDC_LOCAL flag was working correctly before and storing it in the local project directory.  So I'm not sure what the issue is.  Is it possible to explicitly set the binary directory?

**Comment by aleksandr-kotlyar** [comment]
The code didn't change since 06.2020. And earlier code didn't content WDM_LOCAL variable. So there is only one version of code with WDM_LOCAL variable.

<details><summary>git diff</summary>

![image](https://user-images.githubusercontent.com/17043964/137599645-a5513b5a-7a51-4655-b111-ca4c1e9d722f.png)

</details>

P.S. But your comment sounds interesting: 
>  It stores it in the virtualenv/bin directory.

**Comment by aleksandr-kotlyar** [comment]
@stanfordwong6 hi.

`os.environ['WDM_LOCAL']="1"` works fine. Tested on 3.5.4 webdriver-manager now. It creates `.wdm` folder inside the root dir of the project.
https://user-images.githubusercontent.com/17043964/167748018-a019306f-9519-4f47-ae0b-e0a618291d64.mov
