### ISSUE TITLE
ValueError: There is no such driver by url https://msedgedriver.azureedge.net/98.0.1108.51/edgedriver_win64.zip

### ISSUE THREAD

**Issue by kabukabu1000** [SergeyPirogov/webdriver_manager#302]
I've been using it without any problems until today when I suddenly got the error message shown in the title.

[WDM] - ====== WebDriver manager ======
[WDM] - There is no [win64] edgedriver for browser  in cache
[WDM] - Trying to download new driver from https://msedgedriver.azureedge.net/98.0.1108.51/edgedriver_win64.zip
Traceback (most recent call last):
  File "C:\Users\hoge\hogehoge.py", line 325, in <module>
    textcheck()
  File "C:\Users\hoge\hogehoge.py", line 110, in textcheck
    path=EdgeChromiumDriverManager().install()
  File "C:\Users\hoge\anaconda3\lib\site-packages\webdriver_manager\microsoft.py", line 47, in install
    return self._get_driver_path(self.driver)
  File "C:\Users\hoge\anaconda3\lib\site-packages\webdriver_manager\manager.py", line 30, in _get_driver_path
    file = download_file(driver.get_url())
  File "C:\Users\hoge\anaconda3\lib\site-packages\webdriver_manager\utils.py", line 93, in download_file
    validate_response(response)
  File "C:\Users\hoge\anaconda3\lib\site-packages\webdriver_manager\utils.py", line 79, in validate_response
    raise ValueError("There is no such driver by url {}".format(resp.url))
ValueError: There is no such driver by url https://msedgedriver.azureedge.net/98.0.1108.51/edgedriver_win64.zip

**Comment by aleksandr-kotlyar** [comment]
The summary should be `"ValueError: There is no such driver by url https://msedgedriver.azureedge.net/98.0.1108.51/edgedriver_win64.zip"`
because that's the root cause of this stacktrace.

The solution is: setup another version in `EdgeChromiumDriverManager(version=).install()` because Microsoft Edge hadn't released such a driver version. You should take compatible edge driver version for your browser and tests. For example `98.0.1108.50` is the nearest one and should work!

**Comment by sjstevens** [comment]
I have the exact same ValueError ("There is no such driver by url https://msedgedriver.azureedge.net/98.0.1108.51/edgedriver_win64.zip"). I understand the solution, I can temporarily fix the issue by installing version 98.0.1108.51, but shouldn't the question be: why is it tryin' to install this non-existing edgedriver in the first place?

**Comment by aleksandr-kotlyar** [comment]
@sjstevens show the code please.

**Comment by sjstevens** [comment]
> @sjstevens show the code please.

I think you mean this part:
```
elif browser == "edge":
            options = EdgeOptions()
            options.use_chromium = True
            options.set_capability('unhandledPromptBehavior', 'accept')
            if headless_mode:
                options.headless = True
            if incognito_mode:
                options.add_argument("-inprivate")

            if not os.path.exists(AZURE_AGENT_EDGE_DRIVER_PATH):
                driver_path = EdgeChromiumDriverManager().install()
            else:
                driver_path = AZURE_AGENT_EDGE_DRIVER_PATH # This else is present for having the webdriver-manager package working together with the online Azure Agents.

            eventless_driver = Edge(executable_path=driver_path, options=options)
```

**Comment by aleksandr-kotlyar** [comment]
@kabukabu1000 @sjstevens I understood.
1. The edge version determines correctly - 98.X
2. webdriver-manager finds latest edgedriver for windows. LATEST_RELEASE_98
3. webdriver-manager looks at the link what version to download 
 from here https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/LATEST_RELEASE_98
4. And here is 🎉 98.0.1108.51 version
5. webdriver-manager tries to download this version as the latest for 98.X - and forms the url
6. the url is forming correctly, but there is nothing on it!
7. Why?
8. Because Edge have not published 98.0.1108.51 version.
<img width="812" alt="image" src="https://user-images.githubusercontent.com/17043964/154014314-297e9549-e8bc-48f5-8dd4-3ff3bea6b164.png">

And the question goes to EDGE team. It's a bug for all edgedriver users community. webdriver-manager can do nothing here.

You can open issue in the edgedriver repo and ask them to fix the version in LATEST_RELEASE_98 for published or ask them to publish this version.

**Comment by sjstevens** [comment]
Thanks Aleksandr for explaining!

**Comment by aleksandr-kotlyar** [comment]
I see that webdriver-manager takes LATEST_RELEASE or LATEST_STABLE if Edge was not determined correctly. And there is a hole in edgedriver releases - because there can be edgedriver for .51 for mac and win and only .50 for linux - and on linux if we take LATEST_RELEASE_98 or LATEST_STABLE_98 - we will try get .51 driver even if it not available for that platform.

I will try to find a workaround and implement into webdriver-manager and close the hole of release process.
