### ISSUE TITLE
get_browser_version_from_os could be faster

### ISSUE THREAD

**Issue by np-8** [SergeyPirogov/webdriver_manager#323]
The `get_browser_version_from_os` is unnecessarily creating the commands every time `get_browser_version_from_os` is called. Source: [webdriver_manager/webdriver_manager/utils.py](https://github.com/SergeyPirogov/webdriver_manager/blob/9e03223aac79756f05b25f40d1664c4d739e2bfd/webdriver_manager/utils.py#L164)

With version 9e03223:

```
In [2]: from webdriver_manager.utils import *

In [3]: %timeit get_browser_version_from_os('google-chrome')
1.92 s ± 349 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

when `cmd_mapping` is moved out of `get_browser_version_from_os`:

```
In [1]: from webdriver_manager.utils import *

In [2]: %timeit get_browser_version_from_os('google-chrome')
665 ms ± 10.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by SergeyPirogov** [comment]
Do we need additional work here? @np-8 @aleksandr-kotlyar

**Comment by np-8** [comment]
Looking at the current master, inside the [utils.py](https://github.com/SergeyPirogov/webdriver_manager/blob/master/webdriver_manager/core/utils.py#L128), in `get_browser_version_from_os()` it seems that there could be possible improvements available:
1. The `cmd_mapping` is now re-evaluating everything every time `get_browser_version_from_os` is called, and calling `linux_browser_apps_to_cmd` and `windows_browser_apps_to_cmd`. This could be optimized a bit, like done [here](https://github.com/SergeyPirogov/webdriver_manager/commit/9d2f12f56f186ce27a61bd4d97c2e522ead5e07a#diff-71059ecad1f650787c7bc94214a3e3032827a57aba4863cc534a9beec48eaad8R239). This would use a caching mechanism to prevent multiple calls to `linux_browser_apps_to_cmd` and `windows_browser_apps_to_cmd`. I think I did some speed comparisons [here](https://github.com/SergeyPirogov/webdriver_manager/pull/324#issuecomment-1054010544).
2. There is another, *large* optimization possibility mentioned in [this comment](https://github.com/SergeyPirogov/webdriver_manager/pull/324#issuecomment-1054010544). It uses `winreg` module instead of calling Powershell, and is >20.000 times faster. I did not write full solution, but a proof-of-concept [here](https://github.com/SergeyPirogov/webdriver_manager/commit/ba181f9ec2312c2c6bc6cacdf60836c51d49e2bc). It could be used in such way that if the version cannot be read from registry, Powershell is used as fallback. Currently, if registry keys are used (last options in `OSType.WIN` in `get_browser_version_from_os`), they are read using Powershell.

**Comment by Pavocracy** [comment]
I would just like to add here, from my experience you need to be careful about using regex to get the browsers and versions from windows. 

There is an edge case where if the OS has the browser installed, but its never been opened, there is no entry in the registry for it. You can see further details in [this bug report i put up on github community](https://github.community/t/windows-latest-chrome-version-unavaliable-in-registry/228789) because i discovered this bug using githubs action runners.

**Comment by roniemartinez** [comment]
Just throwing my experience here working on related setup in [`pybrowsers`](https://github.com/roniemartinez/browsers).
1. On OSX you can actually read from `.plist` files, using `mdfind` should be fast: https://github.com/roniemartinez/browsers/blob/master/browsers/osx.py
2. On Windows, registry + file version might be one option: https://github.com/roniemartinez/browsers/blob/master/browsers/windows.py
3. Linux is a tricky one because there are several options, one reading the `.desktop` files but of course console based distros don't support this: https://github.com/roniemartinez/browsers/blob/master/browsers/linux.py

**Comment by SergeyPirogov** [comment]
> Just throwing my experience here working on related setup in [`pybrowsers`](https://github.com/roniemartinez/browsers).
> 
> 1. On OSX you can actually read from `.plist` files, using `mdfind` should be fast: https://github.com/roniemartinez/browsers/blob/master/browsers/osx.py
> 2. On Windows, registry + file version might be one option: https://github.com/roniemartinez/browsers/blob/master/browsers/windows.py
> 3. Linux is a tricky one because there are several options, one reading the `.desktop` files but of course console based distros don't support this but works on Github Actions: https://github.com/roniemartinez/browsers/blob/master/browsers/linux.py

Actually, I started using pybrowsers
