### ISSUE TITLE
Allow fallback to *invalid* cache when no connection

### ISSUE THREAD

**Issue by eyaler** [SergeyPirogov/webdriver_manager#416]
I suggest allowing fallback to cache when no internet (or when rate limited), even if the cache is not valid. my reasoning is that i would like to usually poll for the latest version with the short cache of 1 day, but i do not want my code to break when there is no connection.

**Comment by lettow-humain** [comment]
Do you want to use the last installed or the one with the highest version?

**Comment by aleksandr-kotlyar** [comment]
@eyaler hi! 
I am thinking about your suggestion, and I understand your purpose. But as much I think then more questions I get.
For now webdriver-manager at most cases tries to determine browser version installed and if not found - tries to download the latest one. If founds - then tries to download determined version of webdriver. If no connection - it suggests is user is offline or the url is not reachable.

So how do you suggest to fallback to "invalid" cache when wdm doesn't know is here right version or download url has been passed into wdm? 
When user just passes the url - wdm needs to grep the version from url and find it on the disk.
So many steps and if/elses need to be work-around. It's too complicated.

If you don't need to check for updates and controls them by yourself - just set up the version directly and use cache_valid_range as long as you wish to disable cache invalidation.
```python
ChromeDriverManager(version=X.X.X.X, cache_valid_range=100000).install()
```
This should solve your case. Or keep connection alive to keep autoupdate when cache invalidates.
The cache is only for comfortable autoupdate. If you need offline work - just set the max cache_valid_range.


Also I got an idea to add option `cache_valid_range=-1` for eternal cache valid range.

**Comment by lettow-humain** [comment]
@aleksandr-kotlyar I was thinking about that as well and have been looking into the codebase regarding this issue since I was facing this "issue" as well. I also found that I can simply pass a higher `cache_valid_range`. But I didn't want to use the driver I used last but the latest.
So for my project, I am looking into the cache and trying to find the driver with the highest version number. Since this is not saved inside `.wdm/drivers.json`, I am iterating through the drivers and compare versions manually.

```python
def highestWdmVersion(self):
    wdmPath = os.path.join(os.path.expanduser('~'), '.wdm')
    chromeDriverPath = os.path.join(wdmPath, 'drivers/chromedriver')
    chromeDriverArch = os.listdir(chromeDriverPath)[0]
    driverPath = os.path.join(chromeDriverPath, chromeDriverArch)
    localVersions = os.listdir(driverPath)
    localVersionsTuple = [versionToTuple(
        version) for version in localVersions]
    highestVersionTuple = max(localVersionsTuple)
    highestVersion = tupleToVersion(highestVersionTuple)
    highestVersionPath = os.path.join(
        driverPath, highestVersion, 'chromedriver')
    return highestVersionPath
```

These are my helper functions:
```python
def versionToTuple(version):
    return tuple(map(int, version.split('.')))


def tupleToVersion(version):
    return '.'.join(map(str, version))
```
This is not a safe way of doing things but for now, it solved the issue for me. Would be great to have this solved through `wdm` itself.)

When I was thinking about how to implement this in `wdm`, I also thought maybe using `cache_valid_range` to tell `DriverCache` to look for the latest, instead of any within the valid cache range.
My reasoning was that we're trying to download and use the latest version anyway, so we might want to use the cached driver with the highest version too?

**Comment by aleksandr-kotlyar** [comment]
@lettow-humain let me understand, your suggestion about fallback to latest invalid cache only when its “latest” version passed directly to wdm like this 
```python 
ChromeDriverManager(version=“latest”).install()
```
Right?

**Comment by lettow-humain** [comment]
@aleksandr-kotlyar No, I was thinking 

Try to install the latest or use valid local cache of latest:
`ChromeDriverManager().install()`
or
`ChromeDriverManager(cache_valid_range=69).install()`


Try to install a specific version or use valid local cache of specific version:
`ChromeDriverManager(version=X.X.X.X).install()`
or
`ChromeDriverManager(version=X.X.X.X, cache_valid_range=69).install()`

Try to install the latest or use valid local cache of latest within unlimited range: 
`ChromeDriverManager(cache_valid_range=-1).install()`


Try to install the latest or use valid local cache of highest version: 
`ChromeDriverManager(cache_valid_range=0).install()`

The only thing changing would be `cache_valid_range`. It can be used like before but if `cache_valid_range=-1` it means unlimited range. If `cache_valid_range=0` it means fallback to the highest version found in cache regardless of it's range.

To make this easier, we could think about putting the version number in `drivers.json` too.

If we could use it in that way, we would not have to handle falling back to a local version that might be cached but `wdm` would automatically do that. With using a new special value of `0` and/ or `-1` for `cache_valid_range`, we also don't break backwards compatibility.

**Comment by aleksandr-kotlyar** [comment]
@lettow-humain @eyaler what do you expect when fallback to invalid latest cached webdriver will not open browser which was updated to incompatible version?

**Comment by lettow-humain** [comment]
@aleksandr-kotlyar I couldn't find where we check for compatibility but that is a valid point. I'm not sure if I think too highly of wdm's users but if a user looks into how to use `cache_valid_range`, I expect them to understand what it does.

If you decide against changes in that direction, I would suggest that we maybe write the version number into the meta data file so that finding the highest version can be handled a little easier. I'd be happy to contribute to a PR.

**Comment by aleksandr-kotlyar** [comment]
Just set cache_valid_range the value you need. If no connection - fix the connection or modify date in drivers.json

You suggestion of improvement is very complicated to understand and to debug. It will break all the logic if connection is alive but url not found. In this case I am against this change.
