### ISSUE TITLE
read_version_from_cmd returns incomplete version

### ISSUE THREAD

**Issue by luc-ass** [SergeyPirogov/webdriver_manager#448]
Hey there! I am using chromium for scraping inside of a docker container. While installing the chromedriver I request the version of chromium from cmd, but this returns only an incomplete version number, resulting in the download failing.

Code:
```py
...
from webdriver_manager.core.utils import read_version_from_cmd, PATTERN
...
version = read_version_from_cmd("/usr/bin/chromium --version", PATTERN["chromium"])
driver = webdriver.Chrome(
        service=ChromeService(ChromeDriverManager(
            cache_valid_range=7,
            chrome_type=ChromeType.CHROMIUM,
            version=version)
        .install()),
        options=set_chrome_options(),
    )
...
```
Error: 
```cmd
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/106.0.5249/chromedriver_linux64.zip
```
Further research showed, that download was possible by adding `.61` to the version number for this specific download link. Am I missing something?

Tanks for the great module!

**Comment by yusancky** [comment]
I also met the same error (_but with newer Google Chrome_). Did you solve the problem? 

> **Note**
> Unless otherwise noted, Chrome below includes Chromium. 

The problem is clearly because Chromium doesn't release versions one by one. Instead, each version of ChromeDriver supports Chrome with matching major, minor, and build version numbers. For example, [ChromeDriver 109.0.5414.25](https://chromedriver.storage.googleapis.com/index.html?path=109.0.5414.25/) supports all Chrome versions that start with 109.0.5414. 

For me, there are two ways to solve it. 

The first solution is using the right ChromeDriver version number. However, it needs to change after upgrading your browser. 
```diff
driver = webdriver.Chrome(
    service = ChromeService(ChromeDriverManager(
        cache_valid_range = 7,
        chrome_type = ChromeType.CHROMIUM,
-       version = version)
+       version = "106.0.5249.61")
    .install()),
    options = set_chrome_options(),
)
```

There is also another way since Chromium provides an API. You can use `https://chromedriver.storage.googleapis.com/LATEST_RELEASE_109.0.5414` to get the right ChromeDriver version number matching Chrome 109.0.5414 (the value of `version`, or `read_version_from_cmd("/usr/bin/chromium --version", PATTERN["chromium"])`). You can try to use Python to fetch the data.

**Comment by aleksandr-kotlyar** [comment]
@yusancky thank you. You have described how webdriver-manager works. But there is need to write the same code in your project ;)

**Comment by aleksandr-kotlyar** [comment]
@luc-ass there is no need to do what you do. webdriver-manager already does this and checks the version by the same command and downloads the right version to you.

The function read_version_from_cmd works as expected. If you need another behaviour of this function, try your own regexp pattern.

**Comment by aleksandr-kotlyar** [comment]
> > @yusancky thank you. You have described how webdriver-manager works. But there is need to write the same code in your project ;)
> 
> @aleksandr-kotlyar OK. But I noticed that multiple issues raised this same question so it might be great to add the sample code to README.

The code is already inside webdriver-manager sources ;)
