### ISSUE TITLE
webdriver_manager opens google chrome instead of brave

### ISSUE THREAD

**Issue by Emre-Kahveci** [SergeyPirogov/webdriver_manager#465]
my selenium version is "4.6.0" i follow the steps to use with brave as it says on [webdriver_manager ](https://pypi.org/project/webdriver-manager/)site but still google chrome opens

```
# selenium 4
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as BraveService
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.core.utils import ChromeType

driver = webdriver.Chrome(service=BraveService(ChromeDriverManager(chrome_type=ChromeType.BRAVE).install()))

driver.get("https://pypi.org/project/webdriver-manager/")
```

I also tried the selenium 3 steps but the result is still the same

**Comment by aleksandr-kotlyar** [comment]
Try to give selenium webdriver the binary path of your BRAVE
 
Like in opera or like in brave tests of wdm

`options.binary_location = "C:\\Users\\USERNAME\\FOLDERLOCATION\\Opera\\VERSION\\opera.exe"`

**Comment by Emre-Kahveci** [comment]
this method works, but this method was already working independently from webdriver_manager.

**Comment by aleksandr-kotlyar** [comment]
It works because it's a selenium thing, independent from webdriver-manager.
webdriver-manager downloads the version of chromedriver for brave that u need for that selenium thing ;-)
nothing more
webdriver-manager is not a selenium for choosing binary of your browser to start. Its a library for choosing the right webdriver-version for your browser. Just it.
