### ISSUE TITLE
Firefox is not working using GeckoDriverManager

### ISSUE THREAD

**Issue by ZhengYuan-Public** [SergeyPirogov/webdriver_manager#491]
## My Environment 
python==3.10.9
selenium==4.8.0
webdriver-manager==3.8.5

---

## Running the following code,
```
from selenium import webdriver
from selenium.webdriver.firefox.service import Service as FirefoxService
from webdriver_manager.firefox import GeckoDriverManager

driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))
```

---

I got the following error:
`selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line`

---

`GeckoDriverManager().install()` was successful and returned path is `/Users/XXX/.wdm/drivers/geckodriver/macos/0.32/geckodriver`

**Comment by aleksandr-kotlyar** [comment]
@ZhengYuan-Public Hi! How did you installed Firefox?

**Cause**: Your problem is with selenium - it cant find your Firefox binary for some reason it's not in PATH.

**Resolution**: To resolve your issue - place Firefox browser binary to PATH or take a look at Readme how opera example uses browser binary location and passes it to selenium.

Not a webdriver-manager issue. Close.
