### ISSUE TITLE
webdriver_manager tries to download a non-existing version of Chromium

### ISSUE THREAD

**Issue by niconoe** [SergeyPirogov/webdriver_manager#500]
This happens on an Ubuntu machine run via GitHub actions, here is a trace:

```
ERROR: setUpClass (dashboard.tests.selenium.test_integration.PteroisSeleniumTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/early-warning-webapp/early-warning-webapp/dashboard/tests/selenium/test_integration.py", line 48, in setUpClass
    ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()
  File "/home/runner/work/early-warning-webapp/early-warning-webapp/.venv/lib/python3.9/site-packages/webdriver_manager/chrome.py", line 39, in install
    driver_path = self._get_driver_path(self.driver)
  File "/home/runner/work/early-warning-webapp/early-warning-webapp/.venv/lib/python3.9/site-packages/webdriver_manager/core/manager.py", line 30, in _get_driver_path
    file = self._download_manager.download_file(driver.get_url())
  File "/home/runner/work/early-warning-webapp/early-warning-webapp/.venv/lib/python3.9/site-packages/webdriver_manager/core/download_manager.py", line 28, in download_file
    response = self._http_client.get(url)
  File "/home/runner/work/early-warning-webapp/early-warning-webapp/.venv/lib/python3.9/site-packages/webdriver_manager/core/http.py", line 33, in get
    self.validate_response(resp)
  File "/home/runner/work/early-warning-webapp/early-warning-webapp/.venv/lib/python3.9/site-packages/webdriver_manager/core/http.py", line 16, in validate_response
    raise ValueError(f"There is no such driver by url {resp.url}")
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/111.0.5547/chromedriver_linux64.zip
```

When browsing https://chromedriver.storage.googleapis.com, I can see that version 111.0.5547 is indeed not present, but I don't know how/why webdriver manager want to get this one.

Thanks!

**Comment by sk1010k** [comment]
Same issue.
```
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/103.0.5060/chromedriver_linux64.zip
```

- webdriver_manager 3.8.5
- Google Chrome 103.0.5060.53
- Ubuntu 18.04.6 LTS

Possibly PATTERN not matched?
https://github.com/SergeyPirogov/webdriver_manager/blob/d335d7382fcfc8d539da0f098b8bac7a4a307512/webdriver_manager/core/utils.py#L63

**Comment by aleksandr-kotlyar** [comment]
@sk1010k in your case provide code sample please

**Comment by aleksandr-kotlyar** [comment]
@niconoe I understood your issue. It's because chromium not always have a webdriver for X.X.X version pattern or can unpublish it as not stable and make a new version of chromium.

@niconoe The cause of your issue is:

There is no `LATEST_RELEASE_111.0.5547`on the page **today** (may be it was before, may be never was). But you have this version of Chromium. Unfortunately.
Thats not all. webdriver-manager failed to find your unfortunate version and after that fallbacked another url to download  you have seen this url in your stacktrace. Thats fallback was a bug which already has been fixed at master.
Happy news. Fallback with bug is fixed.
Not happy news - you will never see webdriver for X.X.X version of your chromium.

But here are solutions:

1. Set version of webdriver you need for your chromium (if you not trust experimental features of wdm and chromedriver publish politics) 
```python
ChromeDriverManager(version=X.X.X.X).install() # no need to set chrome_type when you pass full version directly
```
2. Take a Chromium version which has a webdriver and when it stops working - upgrade or downgrade to Chromium that has a webdriver.
3. Use this ugly workaround for now. We will try to make it better soon.
```python
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.core.utils import read_version_from_cmd
version = read_version_from_cmd("/path/to/your/chromium --version", r"\d+")
latest_release_url = ChromeDriverManager().driver.latest_release_url + "_" + version
driver_binary = ChromeDriverManager(version="latest", latest_release_url=latest_release_url).install()
```

**Comment by sk1010k** [comment]
@aleksandr-kotlyar 
I don't know why, but now it works.

**Comment by aleksandr-kotlyar** [comment]
> @aleksandr-kotlyar I don't know why, but now it works.

@sk1010k Understood. The Google team not always publish webdriver and browser at the same time even for stable versions. If you are using latest beta/canary/nightly versions of GoogleChrome/Chromium  - it happens more often than for stable releases.
I think may be it was your case today. I am glad that now wdm works fine for you. 🙂
