### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by frankvu191** [SergeyPirogov/webdriver_manager#55]
Hi,
When running test sometimes I got connection error as below
ConnectionError: HTTPConnectionPool(host='chromedriver.storage.googleapis.com', port=80): Max retries exceeded with url: /LATEST_RELEASE (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7dcf609f28>: Failed to establish a new connection: [Errno 110] Connection timed out',))

Kind regards,
Frank

**Comment by AvataCrawlings** [comment]
It might be because of limit to call this resource. I had an idea to provide some settting like validCache time, to not call sites for new versions of drivers every time

**Comment by CARocha** [comment]
Hello how to solve this problem?
i have make functional test when i written the second function to test this error ocurrers
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52824): Max retries exceeded with url: /session/52f894b3-fcfe-426a-94b3-e85183c5e06e/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104eee580>: Failed to establish a new connection: [Errno 61] Connection refused'))

i have use selenium==4.1.3
urllib3==1.26.9
webdriver-manager==3.5.4
Django==4.0.4

i try to make functional tests with selenium any help? o idea?
