### ISSUE TITLE
chrome driver manager, invalid URL

### ISSUE THREAD

**Issue by genobear** [SergeyPirogov/webdriver_manager#550]
Hi, started new env today with webdriver-manager==3.9.1

This code now gets an error 
```python
driver = webdriver.Chrome(service=ChromeService(
        ChromeDriverManager().install()), options=chrome_options)
```

```
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/114.0.5735.199/chromedriver_win32.zip
```

If I revert to 3.8.5 the problem is fixed and I get

```
2023-07-24 14:26:29,918 - INFO -Get LATEST chromedriver version for google-chrome 114.0.5735
2023-07-24 14:26:31,144 - INFO -About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip
[WDM] - Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████| 6.30M/6.30M [00:19<00:00, 338kB/s]
```

I notice the chromedriver is different 114.0.5735.90 vs 114.0.5735.199

If I check here https://chromedriver.storage.googleapis.com/
there is no mention of 114.0.5735.199

**Comment by rtorres90** [comment]
I'm having a similar issue. I'm getting this message:
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/114.0.5735.198/chromedriver_linux64.zip

**Comment by cmin764** [comment]
Yes, I confirm the same with **3.9.1** when attempting to download the _chromedriver_ on Linux:
```
There is no such driver by url https://chromedriver.storage.googleapis.com/114.0.5735/chromedriver_linux64.zip
```

**Comment by ydamit** [comment]
Same. Worked for me when I reverted back to version 3.8.6, so I think there's something wrong with the functionality that identifies the latest version of the driver.

**Comment by SergeyPirogov** [comment]
Chrome changed the way they release drivers. So use 3.9.1 and upgrade chrome to 115

**Comment by cmin764** [comment]
Yes it is, you see, on a Linux machine (that has most probably Chromium installed), the pattern for retrieving the version is `r"\d+\.\d+\.\d+"`, meaning that it has 3 parts. But when composing the final download URL, since all versions which `>=113` (from the peculiar [code logic](https://github.com/SergeyPirogov/webdriver_manager/blob/master/webdriver_manager/drivers/chrome.py#L56)) are considered to be safe to be returned, you end up with an URL like:
```
https://chromedriver.storage.googleapis.com/114.0.5735/chromedriver_linux64.zip
```
instead of a working resolved one like:
```
https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
```
and that's why looking for a Chrome _chromedriver_ usually works, while a Chromium one fails.

----

This is my proposed [change](https://github.com/robocorp/rpaframework/pull/1020/files#diff-07c96aa3e39b1ff0b369c9a1afdf13183c5f7b86a1eb80c95dc1ec328fdfb32fR31-R48) if somebody is willing to submit a PR in this repo:
```python
    def get_latest_release_version(self):
        determined_browser_version = self.get_browser_version_from_os()
        log(f"Get LATEST {self._name} version for {self._browser_type}")
        if determined_browser_version:
            parts = version.parse(determined_browser_version).release
            if len(parts) == 4:
                return determined_browser_version  # got a fully downloadable version

        latest_release_url = (
            self._latest_release_url
            if (self._driver_version == "latest" or determined_browser_version is None)
            else f"{self._latest_release_url}_{determined_browser_version}"
        )
        resp = self._http_client.get(url=latest_release_url)
        return resp.text.rstrip()
```
