### ISSUE TITLE
No such driver version (using 3.9.1)

### ISSUE THREAD

**Issue by zadamsr** [SergeyPirogov/webdriver_manager#561]
Still getting this error even with the newer version 3.9.1, only the error is about an earlier version of chromedriver now (114 instead of 115). 

ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/114.0.5735.248/chromedriver_mac64.zip

Code where the error stacktrace originates from (like the older errors): 
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

**Comment by SSAdvisor** [comment]
See the comments in #546 ; This is not the correct URL for downloading data and is an indication of using an older version of WDM.

**Comment by zadamsr** [comment]
I am using webdriver-manager-3.9.1.

**Comment by zadamsr** [comment]
Update: I was getting the outdated version due to an outdated version of Chrome. Once I updated Chrome to Version 115.0.5790.114 (Official Build) (arm64), I then started getting "Exception: No such driver version 115.0.5790.114 for mac-arm64". 

And then on my linux jenkins / docker machine which routinely installs everything anew, I am getting "Exception: No such driver version 115.0.5790.110 for linux64". 

I've read through the other threads but am still not sure how to resolve this.

**Comment by rosalindkng** [comment]
I'm getting the same error as @zadamsr.
`No such driver version 115.0.5790.114 for mac-arm64`

**Comment by martinharyanto** [comment]
Today, suddenly after trying to run my script, I got this error too..

```
Traceback (most recent call last):
  File "/Users/martinharyanto/PycharmProjects/pythonProject/main.py", line 61, in <module>
    main()
  File "/Users/martinharyanto/PycharmProjects/pythonProject/main.py", line 21, in main
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinharyanto/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/webdriver_manager/chrome.py", line 39, in install
    driver_path = self._get_driver_binary_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinharyanto/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/webdriver_manager/core/manager.py", line 33, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url())
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinharyanto/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/webdriver_manager/drivers/chrome.py", line 59, in get_driver_download_url
    modern_version_url = self.get_url_for_version_and_platform(driver_version_to_download, os_type)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martinharyanto/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/webdriver_manager/drivers/chrome.py", line 94, in get_url_for_version_and_platform
    raise Exception(f"No such driver version {browser_version} for {platform}")
Exception: No such driver version 115.0.5790.114 for mac-arm64
```

**Comment by genobear** [comment]
Using WDM 3.91 now getting Exception: No such driver version 115.0.5790.110 for win32

```
    driver = webdriver.Chrome(service=ChromeService(
        ChromeDriverManager().install()), options=chrome_options
```

Looking at https://googlechromelabs.github.io/chrome-for-testing/

115.0.5790.110 is currently marked as upcoming with a bed red X


https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints

**Comment by abilash-c** [comment]
Is there a permanent fix for this? 

I have included the exact version for now, but I would need to send my automation to others and won't be able to change it every time.

`ChromeDriverManager(driver_version='115.0.5790.102').install()`

**Comment by Daverball** [comment]
Maybe `ChromeDriverManager` should be extended with a boolean option to install the latest available stable version instead, if it can't find a matching version in the known good versions JSON from Google.

This would prevent things from just randomly breaking every time a Chrome Driver release doesn't happen quite in lock step with the Chrome release at the costs of slightly more overhead whenever that situation occurs, since it would need to download and install a different Chrome version, from what is already installed. But it is still much preferred over the CI just breaking randomly every so often.

Of course we could just use the nodejs tools from Google to install the appropriate versions in the CI, but the point of `webdriver_manager` kind of should be, that we don't have to do that.

**Comment by Dipnoid** [comment]
Could we make it so ChromeDriverManager default behaviour installs the latest available driver version if it doesn't match the installed Chrome version?

**Comment by Daverball** [comment]
Since in most cases it's probably just a patch version that's missing and not entire version number, we could probably get away with using this: https://googlechromelabs.github.io/chrome-for-testing/latest-patch-versions-per-build.json

So for `115.0.5790.110` you would strip the last number and look up the value in that JSON, for `115.0.5790` you will get back `115.0.5790.102`

**Comment by Daverball** [comment]
And if it isn't there either, you can use https://googlechromelabs.github.io/chrome-for-testing/latest-versions-per-milestone.json and only use the first number.

**Comment by Dipnoid** [comment]
It works but only if chrome is up to date

**Comment by Daverball** [comment]
> It works but only if chrome is up to date

That's because webdriver_manager only manages the download of the web driver, not of the browser itself, so if you force it to install a version different from your browser version whether or not it still works will depend entirely on how different the two versions are. If it's only apart by one patch it's quite likely it will still work, but what you'd really want to do is also install the browser with that version. Mixing versions is not really a good idea.

That's why I suggested the optional flag that would first install a supported version of the browser if there's no matching web driver version.
