### ISSUE TITLE
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790

### ISSUE THREAD

**Issue by evilgenius786** [SergeyPirogov/webdriver_manager#565]
Chromedriver website says :
_If you are using Chrome version 115 or newer, please consult[ the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/). This page provides convenient [JSON endpoints](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json) for specific ChromeDriver version downloading._

**Comment by mg584** [comment]
Same problem

`ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_mac64.zip`

**Comment by drf5n** [comment]
> Chromedriver website says : _If you are using Chrome version 115 or newer, please consult[ the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/). This page provides convenient [JSON endpoints](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json) for specific ChromeDriver version downloading._

Yes:  https://chromedriver.chromium.org/downloads list only up to 114

https://googlechromelabs.github.io/chrome-for-testing/#stable  and the json link has the current files.

**Comment by FrancoMartinChattigo** [comment]
here there's a possible solution with the version, specify the version
![image](https://github.com/SergeyPirogov/webdriver_manager/assets/104777652/ec6236c3-42d3-457c-a7d7-a3d9499a367b)

**Comment by raylabres** [comment]
Hello! Please, I performed an automation using Python's Selenium and WebDriver-manager, but now it is returning "ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790.10". So searching I found the site: ''https://googlechromelabs.github.io/chrome-for-testing/#stable" which gives me the list of available or unavailable, my current version, is not working because it is waiting for availability, how much how long does it take to stabilize or any ideas to maybe use the old version until this one is available?

**Comment by jamestejada** [comment]
Hey everyone, I was having similar issues as well, but I have found that I was able to recover the correct chromedriver from a production machine. I'm making it available in case you really need it because you just updated your browser and there isn't a non-hacky way to revert back. 

[chromedriver-115.0.5790.110](https://github.com/jamestejada/chromedriver-115.0.5790.110)

NOTE: You to get the webdriver-manager to use the cache, you will have to replace the `drivers.json` in your `.wmd` folder because that is where the record of the cache is stored. In the repo I have given a sample `drivers.json` cache file and have edited the timestamp to be August 30, 2023. Hopefully the issue will be resolved sooner than that. 

I have been testing on Windows 10 machine with latest version of webdriver-manager.

**Comment by A1K2V3** [comment]
I am also having similar issue on linux machine. 

venv/lib/python3.10/site-packages/webdriver_manager/chrome.py:39: in install
    driver_path = self._get_driver_path(self.driver)
venv/lib/python3.10/site-packages/webdriver_manager/core/manager.py:30: in _get_driver_path
    file = self._download_manager.download_file(driver.get_driver_download_url())
venv/lib/python3.10/site-packages/webdriver_manager/drivers/chrome.py:54: in get_driver_download_url
    modern_version_url = self.get_url_for_version_and_platform(driver_version_to_download, os_type)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <webdriver_manager.drivers.chrome.ChromeDriver object at 0x7fe45ec647c0>, browser_version = '115.0.5790.110'
platform = 'linux64'

    def get_url_for_version_and_platform(self, browser_version, platform):
        url = "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json"
        response = self._http_client.get(url)
        data = response.json()
        versions = data["versions"]
        for v in versions:
            if v["version"] == browser_version:
                downloads = v["downloads"]["chromedriver"]
                for d in downloads:
                    if d["platform"] == platform:
                        return d["url"]
    
>       raise Exception(f"No such driver version {browser_version} for {platform}")
E       Exception: No such driver version 115.0.5790.110 for linux64

venv/lib/python3.10/site-packages/webdriver_manager/drivers/chrome.py:89: Exception

**Comment by SergeyPirogov** [comment]
try v4.0.0

**Comment by drf5n** [comment]
Commit  https://github.com/SergeyPirogov/webdriver_manager/commit/d6b66cc5024bb43985d93226c8393fcfa2f92b69 automates specifying the browser path in tests with:

    options = webdriver.ChromeOptions()
    options.binary_location = browsers.get("chrome")["path"]
    driver_path = ChromeDriverManager().install()
    driver = webdriver.Chrome(service=Service(driver_path), options=options)
