### ISSUE TITLE
IndexError: tuple index out of range with 4.0.0

### ISSUE THREAD

**Issue by LkSandeep** [SergeyPirogov/webdriver_manager#586]
Getting `IndexError: tuple index out of range` error, while installing the chrome driver
Environment: Linux
Browser: Chrome 115.0.5790.110
Selenium version: 3.141.0
webdriver-manager: 4.0.0

Error
```python
IndexError: tuple index out of range
self = <webdriver_manager.core.file_manager.FileManager object at 0x7f08784425b0>
archive_file = <webdriver_manager.core.archive.Archive object at 0x7f0878442700>
to_directory = '/home/jenkins/.wdm/gw0/drivers/chromedriver/linux64/115.0.5790.110'

    def __extract_zip(self, archive_file, to_directory):
        zip_class = (LinuxZipFileWithPermissions if self._os_system_manager.get_os_name() == "linux" else zipfile.ZipFile)
        archive = zip_class(archive_file.file_path)
        try:
>           archive.extractall(to_directory)

../../../.local/share/virtualenvs/dsm-frontend-master-regression-test_3-r06qvJTU/lib/python3.8/site-packages/webdriver_manager/core/file_manager.py:65: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.8/zipfile.py:1647: in extractall
    self._extract_member(zipinfo, path, pwd)
/usr/lib/python3.8/zipfile.py:1702: in _extract_member
    shutil.copyfileobj(source, target)
/usr/lib/python3.8/shutil.py:205: in copyfileobj
    buf = fsrc_read(length)
/usr/lib/python3.8/zipfile.py:940: in read
    data = self._read1(n)
/usr/lib/python3.8/zipfile.py:1008: in _read1
    data += self._read2(n - len(data))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <zipfile.ZipExtFile [closed]>, n = 13235

    def _read2(self, n):
        if self._compress_left <= 0:
            return b''
    
        n = max(n, self.MIN_READ_SIZE)
        n = min(n, self._compress_left)
    
        data = self._fileobj.read(n)
        self._compress_left -= len(data)
        if not data:
>           raise EOFError
E           EOFError

/usr/lib/python3.8/zipfile.py:1043: EOFError

During handling of the above exception, another exception occurred:

request = <SubRequest 'driver' for <Function test_app[01 API Key - Create App with API Key, Regenerate, Change Authentication Method - JSON Web Token]>>
pytestconfig = <_pytest.config.Config object at 0x7f08c19e6b50>

    @pytest.fixture(scope="class", autouse=True)
    def driver(request, pytestconfig):
        browser_factory = BrowserFactory.BrowserFactory()
        session.sdkms_data["BROWSER_MODE"] = pytestconfig.getoption("BROWSER_MODE")
        # Initialize WebDriver
>       driver = browser_factory.get_browser(pytestconfig.getoption("BROWSER"), pytestconfig.getoption("BROWSER_MODE"))

roche/conftest.py:48: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
helpers/BrowserFactory.py:44: in get_browser
    executable_path=ChromeDriverManager().install(), options=chrome_options
../../../.local/share/virtualenvs/dsm-frontend-master-regression-test_3-r06qvJTU/lib/python3.8/site-packages/webdriver_manager/chrome.py:40: in install
    driver_path = self._get_driver_binary_path(self.driver)
../../../.local/share/virtualenvs/dsm-frontend-master-regression-test_3-r06qvJTU/lib/python3.8/site-packages/webdriver_manager/core/manager.py:41: in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
../../../.local/share/virtualenvs/dsm-frontend-master-regression-test_3-r06qvJTU/lib/python3.8/site-packages/webdriver_manager/core/driver_cache.py:54: in save_file_to_cache
    files = self.unpack_archive(archive, path)
../../../.local/share/virtualenvs/dsm-frontend-master-regression-test_3-r06qvJTU/lib/python3.8/site-packages/webdriver_manager/core/driver_cache.py:49: in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
../../../.local/share/virtualenvs/dsm-frontend-master-regression-test_3-r06qvJTU/lib/python3.8/site-packages/webdriver_manager/core/file_manager.py:57: in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <webdriver_manager.core.file_manager.FileManager object at 0x7f08784425b0>
archive_file = <webdriver_manager.core.archive.Archive object at 0x7f0878442700>
to_directory = '/home/jenkins/.wdm/gw0/drivers/chromedriver/linux64/115.0.5790.110'

    def __extract_zip(self, archive_file, to_directory):
        zip_class = (LinuxZipFileWithPermissions if self._os_system_manager.get_os_name() == "linux" else zipfile.ZipFile)
        archive = zip_class(archive_file.file_path)
        try:
            archive.extractall(to_directory)
        except Exception as e:
>           if e.args[0] not in [26, 13] and e.args[1] not in [
                "Text file busy",
                "Permission denied",
            ]:
E           IndexError: tuple index out of range

```

**Comment by chermdev** [comment]
I'm having the same issue:

Environment: Linux64
Browser: Chrome 115.0.5790.110
Selenium version: 4.8.0
webdriver-manager: 4.0.0

**Comment by jayph88** [comment]
different error but in same code on windows
webdriver manager: 4.0.0
chrome version:  115.0.5790.110

`    'driver': ChromeDriverManager().install(),
  File "C:\automation_venv\lib\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\automation_venv\lib\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\automation_venv\lib\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\automation_venv\lib\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\automation_venv\lib\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\automation_venv\lib\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\test_runner\\.wdm\\drivers\\chromedriver\\win64\\115.0.5790.110\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\test_runner\\.wdm\\drivers\\chromedriver\\win64\\115.0.5790.110\\chromedriver.exe'`

 I think this happens if somehow webdriver-manager fails to unzip file, not sure why it happens but exception does not handle it gracefully
https://github.com/SergeyPirogov/webdriver_manager/blob/322e160f4ee342ae36ca1f5c49b8d9471f5a809c/webdriver_manager/core/file_manager.py#L65
 
 
 branch to reproduce this issue
https://github.com/jayph88/webdriver_manager/blob/16404838fd258be55e224dcbe0f51095f26c5b5d/webdriver_manager/core/file_manager.py#L65

**Comment by chermdev** [comment]
@jayph88  why do you have a `raise` at the start of the `try`?

**Comment by jayph88** [comment]
I was getting above mentioned exception while running automation. I am not sure why sometimes unzip fails, I raised exception to reproduce issue and I can see exception handling is not working

**Comment by Tiahin** [comment]
I have a similar problem as in #592 
But I see that this issue has a same behavior.
`'C:\\Users\\test_runner\\.wdm\\drivers\\chromedriver\\win64\\115.0.5790.110\\chromedriver-win32\\chromedriver.exe' ->`
win64 vs driver for win32 - is it correct?
