### ISSUE TITLE
chromedriver update download way

### ISSUE THREAD

**Issue by luzihang123** [SergeyPirogov/webdriver_manager#617]
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116.0.5845

**Comment by aleksandr-kotlyar** [comment]
Upgrade to 4.0.0+ feel free to reopen if issue still actual and add more info next time

**Comment by konstantincheban** [comment]
Chrome version: 116.0.5845.140 (Official Build) (x86_64)
webdriver_manager version: 4.0.1

Even with version 4.0.0+ it does not work because https://chromedriver.storage.googleapis.com/ doesn't have this latest version of webdriver. it's available only here: https://googlechromelabs.github.io/chrome-for-testing/#stable. Is there any way to use custom url or how can I use my local webdriver?

**Comment by luzihang123** [comment]
> Chrome version: 116.0.5845.140 (Official Build) (x86_64) webdriver_manager version: 4.0.1
> 
> Even with version 4.0.0+ it does not work because https://chromedriver.storage.googleapis.com/ doesn't have this latest version of webdriver. it's available only here: https://googlechromelabs.github.io/chrome-for-testing/#stable. Is there any way to use custom url or how can I use my local webdriver?

```
import undetected_chromedriver as uc
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

driver = uc.Chrome(driver_executable_path='/usr/local/bin/chromedriver' ) # macos
driver.get("https://www.google.com")
```

**Comment by konstantincheban** [comment]
nvm, sorry for the confusion, I had venv issues, version 4.0.0 works fine.
